version: '3.4'
services:

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/docker/nextcloud/config:/config
      - /srv/docker/nextcloud/data:/data
      - /downloads:/files/downloads
      - /media:/files/media
      - /users:/files/users
    ports:
      - 8443:443
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - '8000:8000'
      - '9443:9443'
      - '9000:9000'
    volumes:
      - /srv/docker/portainer/data:/data
    restart: unless-stopped

  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - /srv/docker/nginx_proxy_manager/data:/data
      - /srv/docker/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=0 #! Potential security risk set as 0
      - PGID=0 #! Potential security risk set as 0
      - TZ=Europe/London
    volumes:
      - /srv/docker/syncthing:/config
      - /users:/data/users
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr
    ports:
      - 5690:5690
    volumes:
      - /srv/docker/wizarr:/data/database
    environment:
      - APP_URL=https://invite.sharsant.com
      - DISABLE_BUILTIN_AUTH=false
      - TZ=Europe/London
