version: '3.4'
services:

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/docker/nextcloud/config:/config
      - /srv/docker/nextcloud/data:/data
      - /downloads:/files/downloads
      - /media:/files/media
      - /users:/files/users
    ports:
      - 8443:443
    restart: unless-stopped

  photoview_db:
    image: mariadb:10.5
    container_name: photoview_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=${PHOTOVIEW_SECRET}
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - /srv/docker/photoview/db:/var/lib/mysql

  photoview:
    image: viktorstrate/photoview:latest
    container_name: photoview
    restart: unless-stopped
    ports:
      - 8001:80
    depends_on:
      - photoview_db
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:${PHOTOVIEW_SECRET}@tcp(photoview_db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
    volumes:
      - /srv/docker/photoview/api_cache:/app/cache
      - /users/steve/pictures/:/photos/steve:ro
      - /users/miki/photos/:/photos/miki:ro

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - '8000:8000'
      - '9443:9443'
      - '9000:9000'
    volumes:
      - /srv/docker/portainer/data:/data
    restart: unless-stopped

  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - /srv/docker/nginx_proxy_manager/data:/data
      - /srv/docker/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=0 #! Potential security risk set as 0
      - PGID=0 #! Potential security risk set as 0
      - TZ=Europe/London
    volumes:
      - /srv/docker/syncthing:/config
      - /users:/data/users
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  wyl:
    image: aceberg/watchyourlan:latest
    container_name: wyl
    hostname: wyl
    environment:
      - IFACE=eth0
      - TZ=Europe/London
      - THEME=darkly
      - GUIIP=${GUIIP}
      - GUIPORT=8840
    volumes:
      - /srv/docker/wyl:/data
    network_mode: 'host'
    restart: unless-stopped
