services:
  # tide-invite:
  #   image: ghcr.io/steveharsant/tide-invite:latest
  #   container_name: tide-invite
  #   hostname: tide-invite
  #   volumes:
  #     - ${DOCKER_PATH}/tide-invite/config:/config
  #   environment:
  #     - INVITE_DAY=${INVITE_DAY}
  #     - INVITE_TIME=${INVITE_TIME}
  #     - WILLYWEATHER_API_KEY=${WILLYWEATHER_API_KEY}
  #     - WILLYWEATHER_LOCATION_ID=${WILLYWEATHER_LOCATION_ID}
  #     - ATTENDEES=${ATTENDEES} # comma separated value
  #     - DEBUG=${DEBUG}
  #   restart: unless-stopped

