version: '3.4'
services:

  deluge:
    image: kabe0/deluge-windscribe:latest
    container_name: deluge
    restart: unless-stopped
    environment:
      - VPN_USERNAME=${VPN_USERNAME}
      - VPN_PASSWORD=${VPN_PASSWORD}
      - VPN_LOCATION=${VPN_LOCATION}
    volumes:
      - /mnt/ext0/downloads:/downloads
    ports:
      - 8112:8112
      - 58846:58846
    dns:
      - 8.8.8.8
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /mnt/ext0/media:/media
      - /srv/docker/emby:/config
      - /srv/docker/emby/custom-cont-init.d:/custom-cont-init.d:ro
    ports:
      - 8096:8096
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    ports:
      - 8191:8191
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true
    volumes:
      - /srv/docker/jackett/config:/config
      - /srv/docker/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /srv/docker/radarr:/config
      - /mnt/ext0/media/movies:/movies
      - /mnt/ext0/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: 'GMT'
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/ext0/downloads:/downloads:z
      - /srv/docker:/docker:z
      - /mnt/ext0/media:/media:z
      - /mnt/ext0/users:/users:z
    command: '-s "docker;/docker;yes;no;no;${SMB_USER};${SMB_USER};${SMB_USER};docker" -s "downloads;/downloads;yes;no;no;${SMB_USER};${SMB_USER};${SMB_USER};downloads" -s "media;/media;yes;no;no;${SMB_USER};${SMB_USER};${SMB_USER};media" -s "users;/users;yes;no;no;${SMB_USER};${SMB_USER};${SMB_USER};users" -u "${SMB_USER};${SMB_PASS}" -p'

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /srv/docker/sonarr:/config
      - /mnt/ext0/media/tv:/tv
      - /mnt/ext0/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - /srv/docker/uptime_kuma:/app/data
    ports:
      - '3001:3001'
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
      - WATCHTOWER_SCHEDULE=0 0 19 * * SUN
      - WATCHTOWER_TIMEOUT=1800s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
