services:
  doods:
    image: snowzach/doods2:latest
    container_name: doods
    restart: unless-stopped
    ports:
      - "8080:8080"   # REST API
      - "8443:8443"   # gRPC
    volumes:
      - ${DOCKER_PATH}/doods/config:/opt/doods/config
      - ${DOCKER_PATH}/doods/models:/opt/doods/models
    environment:
      - CONFIG=/opt/doods/config/config.yaml
      
  whisper:
    image: lscr.io/linuxserver/faster-whisper:latest
    container_name: whisper
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WHISPER_MODEL=small # Options: tiny, base, small, medium
      - WHISPER_LANG=en
      - WHISPER_BEAM=1
    ports:
      - "10300:10300"
    volumes:
      - ${DOCKER_PATH}/whisper/data:/config
    

  piper:
    image: lscr.io/linuxserver/piper:latest
    container_name: piper
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PIPER_VOICE=en_GB-alba-medium
    ports:
      - "10200:10200"
    volumes:
      - ${DOCKER_PATH}/piper/data:/config
