version: '3.4'
services:

  server:
    image: jetbrains/teamcity-server:latest
    container_name: server
    volumes:
      - /srv/docker/teamcity/server/data:/data/teamcity_server/datadir
      - /srv/docker/teamcity/server/logs:/opt/teamcity/logs
    ports:
      - 8111:8111

  agent1:
    depends_on:
      - server
    image: custom-minimal-agent:latest
    container_name: agent1
    environment:
      - SERVER_URL=${TEAMCITY_SERVER_URL}
      - AGENT_NAME=agent1
    volumes:
      - /srv/docker/teamcity/agent1:/data/teamcity_agent/conf

  agent2:
    depends_on:
      - server
    image: custom-minimal-agent:latest
    container_name: agent2
    environment:
      - SERVER_URL=${TEAMCITY_SERVER_URL}
      - AGENT_NAME=agent2
    volumes:
      - /srv/docker/teamcity/agent2:/data/teamcity_agent/conf

  agent3:
    depends_on:
      - server
    image: custom-minimal-agent:latest
    container_name: agent3
    environment:
      - SERVER_URL=${TEAMCITY_SERVER_URL}
      - AGENT_NAME=agent3
    volumes:
      - /srv/docker/teamcity/agent3:/data/teamcity_agent/conf
