services:
  server:
    image: jetbrains/teamcity-server:latest
    container_name: server
    volumes:
      - /data/docker/teamcity/server/data:/data/teamcity_server/datadir
      - /data/docker/teamcity/server/logs:/opt/teamcity/logs
    ports:
      - 8111:8111
