version: '3.4'
services:
  photoview_db:
    image: mariadb:10.5
    container_name: photoview_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=${PHOTOVIEW_SECRET}
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - /srv/docker/photoview/db:/var/lib/mysql

  photoview:
    image: viktorstrate/photoview:latest
    container_name: photoview
    restart: unless-stopped
    ports:
      - 8001:80
    depends_on:
      - photoview_db
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:${PHOTOVIEW_SECRET}@tcp(photoview_db)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=80
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
    volumes:
      - /srv/docker/photoview/api_cache:/app/cache
      - /users/steve/pictures/:/photos/steve:ro
      - /users/miki/photos/:/photos/miki:ro
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 25m
