version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: 'GMT'
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /downloads:/downloads:z
      - /media:/media:z
      - /users:/users:z
    command: '-s "downloads;/downloads;yes;no;no;${SMB_USER};${SMB_USER};${SMB_USER};downloads" -s "media;/media;yes;no;no;${SMB_USER};${SMB_USER};${SMB_USER};media" -s "users;/users;yes;no;no;${SMB_USER};${SMB_USER};${SMB_USER};users" -u "${SMB_USER};${SMB_PASS}" -p'
