version: '3.4'
services:

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: steve-proxy
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - NETDATA_CLAIM_TOKEN=${NETDATA_CLAIM_TOKEN}
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=

  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: 'proxy-manager-db'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: 'npm'
      DB_MYSQL_PASSWORD: "${PROXYMANAGER_PASSWORD}"
      DB_MYSQL_NAME: 'npm'
      DISABLE_IPV6: 'true'
    volumes:
      - /srv/docker/nginx_proxy_manager/data:/data
      - /srv/docker/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  proxy-manager-db:
    image: 'jc21/mariadb-aria:latest'
    container_name: proxy-manager-db
    environment:
      MYSQL_ROOT_PASSWORD: "${PROXYMANAGER_PASSWORD}"
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: "${PROXYMANAGER_PASSWORD}"
    volumes:
      - /srv/docker/nginx_proxy_manager/mysql:/var/lib/mysql
    restart: unless-stopped

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
