services:
  huntarr:
    image: ghcr.io/plexguide/huntarr:latest
    container_name: huntarr
    restart: always
    ports:
      - "9705:9705"
    volumes:
      - ${DOCKER_PATH}/huntarr:/config
    environment:
      - TZ=${TIMEZONE}

  purgarr:
    image: ghcr.io/steveharsant/purgarr:latest
    container_name: purgarr
    environment:
      - LOG_OUTPUT=web
      - QBIT_URL=${QBIT_URL}
      - QBIT_PASSWORD=${QBIT_PASSWORD}
      - QBIT_TOKEN_REFRESH_INTERVAL=${QBIT_TOKEN_REFRESH_INTERVAL}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - SONARR_URL=${SONARR_URL}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - RADARR_URL=${RADARR_URL}
    restart: unless-stopped


