version: '3.4'
services:

  deluge:
    image: kabe0/deluge-windscribe:latest
    container_name: deluge
    restart: unless-stopped
    environment:
      - VPN_USERNAME=${VPN_USERNAME}
      - VPN_PASSWORD=${VPN_PASSWORD}
      - VPN_LOCATION=${VPN_LOCATION}
    volumes:
      - /downloads:/downloads
    ports:
      - 8112:8112
      - 58846:58846
    dns:
      - 8.8.8.8
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    ports:
      - 8191:8191
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true
    volumes:
      - /srv/docker/jackett/config:/config
      - /srv/docker/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/docker/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /srv/docker/radarr:/config
      - /media/movies:/movies
      - /downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /srv/docker/sonarr:/config
      - /media/tv:/tv
      - /downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Extra node port
    environment:
      - internalNode=false
      - nodeID=InternalNode
      - PGID=1000
      - PUID=1000
      - serverIP=0.0.0.0
      - serverPort=8266
      - TZ=Europe/London
      - UMASK_SET=002
      - webUIPort=8265
    volumes:
      - /srv/docker/tdarr/server:/app/server
      - /srv/docker/tdarr/config:/app/configs
      - /srv/docker/tdarr/logs:/app/logs
      - /media:/media

  # ytdl:
  #   image: tzahi12345/youtubedl-material:latest
  #   container_name: ytdl
  #   depends_on:
  #     - ytdl-db
  #   environment:
  #     - ALLOW_CONFIG_MUTATIONS='true'
  #     - ytdl_mongodb_connection_string='mongodb://ytdl-db:27017'
  #     - ytdl_use_local_db='false'
  #     - write_ytdl_config='true'
  #   volumes:
  #     - /srv/docker/ytdl/appdata:/app/appdata
  #     - /srv/docker/ytdl/subscriptions:/app/subscriptions
  #     - /srv/docker/ytdl/users:/app/users
  #     - /downloads/.ytdl/audio:/app/audio
  #     - /downloads/.ytdl/video:/app/video
  #   ports:
  #     - "8998:17442"
  #   restart: unless-stopped

  # ytdl-db:
  #   image: mongo
  #   container_name: ytdl-db
  #   logging:
  #     driver: "none"
  #   volumes:
  #     - /srv/docker/ytdl/db/:/data/db
  #   ports:
  #     - "27017:27017"
  #   restart: unless-stopped
