version: '3.4'
services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - /srv/docker/grafana/config:/var/lib/grafana
    restart: unless-stopped

  grafana-db:
    image: influxdb:latest
    container_name: grafana-db
    ports:
      - 8086:8086
    volumes:
      - /srv/docker/grafana/db:/var/lib/influxdb
    restart: unless-stopped

  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: steve-monitor
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - NETDATA_CLAIM_TOKEN=${NETDATA_CLAIM_TOKEN}
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - /srv/docker/uptime_kuma:/app/data
    ports:
      - '3001:3001'
    restart: unless-stopped

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
